name: test471
on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every day at midnight
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: test475
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          rclone copy ddi:"pahe/" photos:album/pahemovies --transfers 50 -v --stats-one-line --stats=15s --ignore-existing --drive-chunk-size 128M --drive-acknowledge-abuse
